name: ibm
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - _py-xgboost-mutex=2.0
  - altair=5.5.0
  - aom=3.6.0
  - arrow-cpp=21.0.0
  - asttokens=3.0.0
  - attrs=24.3.0
  - aws-c-auth=0.9.0
  - aws-c-cal=0.9.2
  - aws-c-common=0.12.4
  - aws-c-compression=0.3.1
  - aws-c-event-stream=0.5.6
  - aws-c-http=0.10.4
  - aws-c-io=0.21.4
  - aws-c-mqtt=0.13.3
  - aws-c-s3=0.8.7
  - aws-c-sdkutils=0.2.4
  - aws-checksums=0.2.7
  - aws-crt-cpp=0.34.0
  - aws-sdk-cpp=1.11.638
  - blas=1.0
  - blinker=1.9.0
  - bottleneck=1.4.2
  - brotlicffi=1.0.9.2
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.10.5
  - cachetools=5.5.1
  - cairo=1.18.4
  - category_encoders=2.8.1
  - certifi=2025.10.5
  - cffi=2.0.0
  - charset-normalizer=3.3.2
  - click=8.2.1
  - colorama=0.4.6
  - comm=0.2.3
  - contourpy=1.3.1
  - cramjam=2.9.1
  - cycler=0.11.0
  - cyrus-sasl=2.1.28
  - dav1d=1.2.1
  - debugpy=1.8.16
  - decorator=5.2.1
  - exceptiongroup=1.3.0
  - executing=2.2.1
  - expat=2.7.1
  - fastparquet=2024.11.0
  - fontconfig=2.15.0
  - fonttools=4.60.1
  - freetype=2.13.3
  - fribidi=1.0.10
  - fsspec=2025.7.0
  - gflags=2.2.2
  - gitdb=4.0.12
  - gitpython=3.1.43
  - glog=0.5.0
  - graphite2=1.3.14
  - harfbuzz=10.2.0
  - icu=73.1
  - idna=3.7
  - imbalanced-learn=0.14.0
  - importlib-metadata=8.7.0
  - intel-openmp=2025.0.0
  - ipykernel=6.30.1
  - ipython=9.6.0
  - ipython_pygments_lexers=1.1.1
  - jedi=0.19.2
  - jinja2=3.1.6
  - joblib=1.5.2
  - jpeg=9f
  - jsonschema=4.25.0
  - jsonschema-specifications=2023.7.1
  - jupyter_client=8.6.3
  - jupyter_core=5.8.1
  - kagglehub=0.3.8
  - kiwisolver=1.4.8
  - lcms2=2.16
  - ld_impl_linux-64=2.44
  - lerc=4.0.0
  - libabseil=20250127.0
  - libavif=1.1.1
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcups=2.4.2
  - libcurl=8.15.0
  - libdeflate=1.22
  - libdrm=2.4.124
  - libedit=3.1.20230828
  - libegl=1.7.0
  - libev=4.33
  - libevent=2.1.12
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libgl=1.7.0
  - libglib=2.84.2
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libgomp=11.2.0
  - libgrpc=1.71.0
  - libiconv=1.16
  - libkrb5=1.21.3
  - libllvm15=15.0.7
  - libmpdec=4.0.0
  - libnghttp2=1.57.0
  - libopengl=1.7.0
  - libpciaccess=0.18
  - libpng=1.6.50
  - libpq=17.6
  - libprotobuf=5.29.3
  - libre2-11=2024.07.02
  - libsodium=1.0.20
  - libssh2=1.11.1
  - libstdcxx-ng=11.2.0
  - libthrift=0.15.0
  - libtiff=4.7.0
  - libuuid=1.41.5
  - libwebp-base=1.3.2
  - libxcb=1.17.0
  - libxgboost=3.0.1
  - libxkbcommon=1.9.1
  - libxml2=2.13.8
  - libzlib=1.3.1
  - lightgbm=4.6.0
  - lmdb=0.9.31
  - lz4-c=1.9.4
  - markupsafe=3.0.2
  - matplotlib=3.10.6
  - matplotlib-base=3.10.6
  - matplotlib-inline=0.1.7
  - mesalib=25.1.5
  - mkl=2025.0.0
  - mkl-service=2.5.2
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - mysql=9.3.0
  - mysql-client=9.3.0
  - mysql-common=9.3.0
  - mysql-devel=9.3.0
  - mysql-libs=9.3.0
  - mysql-server=9.3.0
  - narwhals=2.7.0
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - numexpr=2.11.0
  - numpy=2.3.3
  - numpy-base=2.3.3
  - openjpeg=2.5.2
  - openldap=2.6.10
  - openssl=3.0.18
  - orc=2.2.0
  - packaging=25.0
  - pandas=2.3.3
  - parso=0.8.5
  - patsy=1.0.1
  - pcre2=10.42
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=11.3.0
  - pip=25.2
  - pixman=0.46.4
  - platformdirs=4.4.0
  - prompt-toolkit=3.0.52
  - protobuf=5.29.3
  - psutil=7.0.0
  - pthread-stubs=0.3
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - py-xgboost=3.0.1
  - pyarrow=21.0.0
  - pycparser=2.23
  - pygments=2.19.2
  - pyparsing=3.2.0
  - pyqt=6.9.1
  - pyqt6-sip=13.10.2
  - pysocks=1.7.1
  - python=3.13.7
  - python-dateutil=2.9.0post0
  - python-tzdata=2025.2
  - python_abi=3.13
  - pytz=2025.2
  - pyyaml=6.0.2
  - pyzmq=27.1.0
  - qtbase=6.9.2
  - qtdeclarative=6.9.2
  - qtsvg=6.9.2
  - qttools=6.9.2
  - qtwayland=6.9.2
  - qtwebchannel=6.9.2
  - qtwebsockets=6.9.2
  - re2=2024.07.02
  - readline=8.3
  - referencing=0.30.2
  - requests=2.32.5
  - rpds-py=0.22.3
  - s2n=1.5.14
  - scikit-learn=1.7.2
  - scipy=1.16.2
  - seaborn=0.13.2
  - setuptools=80.9.0
  - sip=6.12.0
  - six=1.17.0
  - smmap=4.0.0
  - snappy=1.2.1
  - spirv-tools=2025.1
  - sqlite=3.50.2
  - stack_data=0.6.3
  - statsmodels=0.14.5
  - streamlit=1.50.0
  - tbb=2022.0.0
  - tbb-devel=2022.0.0
  - tenacity=9.1.2
  - threadpoolctl=3.5.0
  - tk=8.6.15
  - toml=0.10.2
  - tornado=6.5.1
  - tqdm=4.67.1
  - traitlets=5.14.3
  - typing-extensions=4.15.0
  - typing_extensions=4.15.0
  - tzdata=2025b
  - urllib3=2.5.0
  - utf8proc=2.6.1
  - watchdog=6.0.0
  - wayland=1.24.0
  - wcwidth=0.2.14
  - wheel=0.45.1
  - xcb-util=0.4.1
  - xcb-util-cursor=0.1.5
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.1
  - xcb-util-renderutil=0.3.10
  - xcb-util-wm=0.4.2
  - xgboost=3.0.1
  - xkeyboard-config=2.44
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.1
  - xorg-libxrandr=1.5.4
  - xorg-libxrender=0.9.12
  - xorg-libxshmfence=1.3.3
  - xorg-libxxf86vm=1.1.6
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.23.0
  - zlib=1.3.1
  - zstd=1.5.7
